#!/bin/sh
# Packages the splitter source into the two forms that leave this repo:
#
#   app/(payload)/admin/tools/split/split-html.ts   the hosted copy (#81),
#     a generated module the /admin/tools/split route imports -- a module
#     cannot fail to be bundled, where a loose file has to survive the deploy
#   tools/scan-splitter/Coin Scan Splitter.html     the sendable file
#
# The hosted copy is generated, never edited: the one time a hand-packaged
# copy drifted from the source it cost an evening. `splitter-hosted.spec.ts`
# fails the build if this script was not re-run after a source change.
set -e
cd "$(dirname "$0")"

wrap() {
  printf '<!doctype html>\n<html lang="en"><head><meta charset="utf-8">\n'
  printf '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
  printf '</head><body style="margin:0">\n'
  cat coin-splitter.html
  printf '</body></html>\n'
}

wrap | node -e '
  let html = "";
  process.stdin.on("data", (chunk) => (html += chunk));
  process.stdin.on("end", () => {
    process.stdout.write(
      "// Generated by tools/scan-splitter/package.sh -- do not edit.\n" +
        "// The exact source of tools/scan-splitter/coin-splitter.html, wrapped\n" +
        "// and stringified. tests/splitter-hosted.spec.ts fails CI if this\n" +
        "// module was not regenerated after a source change.\n" +
        "export const splitterHtml = " + JSON.stringify(html) + ";\n",
    );
  });
' > "../../app/(payload)/admin/tools/split/split-html.ts"
wrap > "Coin Scan Splitter.html"
echo "packaged: $(grep -o "VERSION = '[^']*'" coin-splitter.html)"
