import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { expect, test } from '@playwright/test';

/**
 * Guards on the hosted Scan Splitter (#74 phase 1).
 *
 * The tool's logic has its own suite in tools/scan-splitter/. These tests only
 * defend the two properties that hosting adds -- the URL serves, and the
 * hosted copy is the source, not a cousin of it. The second one exists
 * because a hand-packaged copy drifted from the source once and shipped a
 * missing fix; the copy is generated by package.sh and this test makes
 * forgetting to run it a red build instead of a quiet divergence.
 */

const ROOT = process.cwd();

test('the hosted copy embeds the splitter source verbatim', () => {
  const source = readFileSync(
    join(ROOT, 'tools/scan-splitter/coin-splitter.html'),
    'utf8',
  );
  const hosted = readFileSync(join(ROOT, 'public/tools/split.html'), 'utf8');

  expect(
    hosted.includes(source),
    'public/tools/split.html was not regenerated -- run tools/scan-splitter/package.sh',
  ).toBe(true);
});

test('the splitter serves at its unlinked URL', async ({ page }) => {
  const response = await page.goto('/tools/split.html');
  expect(response?.status()).toBe(200);

  // The version stamp is the whole point of the header -- "which build do
  // you have open" must be answerable from a phone screenshot.
  await expect(page).toHaveTitle(/Scan Splitter v\d+/);
  await expect(page.locator('#version')).toContainText(/v\d+/);

  // The drop bed is the tool; if it rendered, the page's JS ran.
  await expect(page.locator('#bed')).toBeVisible();
});

test('nothing on the site links to it', async ({ page }) => {
  await page.goto('/');
  const links = await page
    .locator('a[href*="split"]')
    .count();
  expect(links, 'the splitter is for Mike, not for visitors').toBe(0);
});
