import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { expect, test } from '@playwright/test';

/**
 * Guards on the hosted Scan Splitter (#81 -- behind Payload auth at
 * /admin/tools/split).
 *
 * The tool's logic has its own suite in tools/scan-splitter/. These tests only
 * defend the properties that hosting adds -- the gate holds, and the hosted
 * copy is the source, not a cousin of it. The second one exists because a
 * hand-packaged copy drifted from the source once and shipped a missing fix;
 * the copy is generated by package.sh and this test makes forgetting to run
 * it a red build instead of a quiet divergence.
 *
 * An authenticated 200 is deliberately not asserted here: CI's database has
 * no fixture user, and this issue does not buy user-seeding infrastructure.
 * The authed path is verified manually against a dev server with a real
 * login (see #81).
 */

const ROOT = process.cwd();

test('the generated module embeds the splitter source verbatim', () => {
  const source = readFileSync(
    join(ROOT, 'tools/scan-splitter/coin-splitter.html'),
    'utf8',
  );
  const generated = readFileSync(
    join(ROOT, 'app/(payload)/admin/tools/split/split-html.ts'),
    'utf8',
  );

  // The module holds the HTML JSON.stringified; containment is checked in
  // that encoding so the comparison is against what actually ships.
  const encodedSource = JSON.stringify(source).slice(1, -1);

  expect(
    generated.includes(encodedSource),
    'split-html.ts was not regenerated -- run tools/scan-splitter/package.sh',
  ).toBe(true);
});

test('logged out, the splitter URL is a login redirect that leaks no tool', async ({
  request,
}) => {
  const response = await request.get('/admin/tools/split', {
    maxRedirects: 0,
  });

  expect([302, 303]).toContain(response.status());
  // Relative, not just containing /admin/login: an absolute Location built
  // from the request origin shipped a redirect to localhost:3000 from behind
  // the production proxy. Relative resolves on whatever host the browser is
  // actually on.
  expect(response.headers()['location']).toMatch(/^\/admin\/login/);

  // The gate is only a gate if the body carries nothing: the tool's HTML must
  // not ride along on an unauthenticated response.
  const body = await response.text();
  expect(body).not.toContain('coin-splitter');
  expect(body).not.toContain('Scan Splitter v');
});

test('the old unauthenticated URL is gone', async ({ request }) => {
  const response = await request.get('/tools/split.html');
  expect(response.status()).toBe(404);
});

test('nothing on the site links to it', async ({ page }) => {
  await page.goto('/');
  const links = await page
    .locator('a[href*="split"]')
    .count();
  expect(links, 'the splitter is for Mike, not for visitors').toBe(0);
});
